title: DEV
description: DEV
github_username: asturnus

url: "https://asturnus.one"
baseurl: ""

# Github and twitter are optional:
minima:
  social_links:
    github: asturnus

# Set this to true to get LaTeX math equation support
use_math: true

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to display tags on each post
show_tags: true

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

future: true
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-relative-links

remote_theme: jekyll/minima

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
